# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtSignin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from MainPage import Ui_MainWindow02
from CreateAccount import Ui_Create_Account_MainWindow03

from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_MainWindow01(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(773, 484)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(140, 60, 541, 361))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 521, 341))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(Images/17973908.jpg);\n"
"border-radius: 30px;")
        self.label.setMidLineWidth(9)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(360, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(self.widget)
        self.loginButton.setGeometry(QtCore.QRect(370, 230, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.loginButton.setFont(font)
        self.loginButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 5px;")
        self.loginButton.setObjectName("loginButton")

        self.CreateAcc = QtWidgets.QPushButton(self.widget)
        self.CreateAcc.setGeometry(QtCore.QRect(260, 320, 81, 16))
        font = QtGui.QFont()
        font.setUnderline(True)
        self.CreateAcc.setFont(font)
        self.CreateAcc.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        self.CreateAcc.setObjectName("Create_Account")

        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(100, 90, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")


        self.forgetPass = QtWidgets.QPushButton(self.widget)
        self.forgetPass.setGeometry(QtCore.QRect(430, 320, 81, 16))
        font = QtGui.QFont()
        self.forgetPass.setFont(font)
        self.forgetPass.setStyleSheet("background-color: rgba(0, 0, 0, 0);")
        font.setUnderline(True)
        self.forgetPass.setFont(font)
        self.forgetPass.setObjectName("forgetPass")

        
        
        
        # self.CreateAcc = QtWidgets.QLabel(self.widget)
        # self.CreateAcc.setGeometry(QtCore.QRect(260, 320, 81, 16))
        # font = QtGui.QFont()
        # font.setUnderline(True)
        # self.CreateAcc.setFont(font)
        # self.CreateAcc.setObjectName("Create_Account")


        self.UserName = QtWidgets.QLineEdit(self.widget)
        self.UserName.setGeometry(QtCore.QRect(320, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.UserName.setFont(font)
        self.UserName.setAutoFillBackground(False)
        self.UserName.setStyleSheet("border: none;")
        self.UserName.setMaxLength(10)
        self.UserName.setCursorPosition(0)
        self.UserName.setClearButtonEnabled(False)
        self.UserName.setObjectName("UserName")


        self.Pass = QtWidgets.QLineEdit(self.widget)
        self.Pass.setGeometry(QtCore.QRect(320, 170, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Pass.setFont(font)
        self.Pass.setAutoFillBackground(False)
        self.Pass.setStyleSheet("border: none;")
        self.Pass.setMaxLength(10)
        self.Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pass.setCursorPosition(0)
        self.Pass.setClearButtonEnabled(False)
        self.Pass.setObjectName("pass")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(190, 130, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Sign In"))
        self.loginButton.setText(_translate("MainWindow", "LOGIN"))
        self.label_3.setText(_translate("MainWindow", "DEMO PAGE"))
        self.forgetPass.setText(_translate("MainWindow", "Forget Password"))
        self.CreateAcc.setText(_translate("MainWindow", "Create Account"))
        self.UserName.setPlaceholderText(_translate("MainWindow", "User Name"))
        self.Pass.setPlaceholderText(_translate("MainWindow", "Password"))
        self.label_5.setText(_translate("MainWindow", "Learning"))
        self.loginButton.clicked.connect(self.open_new_window)
        self.CreateAcc.clicked.connect(self.open_new_window1)
        
        self.login()

    def login(self):
        connection = sqlite3.connect("anil.db")
        results=connection.execute("SELECT USER_NAME, PASSWORD FROM USER_CREDENTIALS") 
        for x in results:
            print("usre:"+str(x[0])+"   passwd :"+str(x[1]))
        connection.close()   
    
    def open_new_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_MainWindow02()
        self.ui.setupUi(self.window)           
        self.window.show()
    
    def open_new_window1(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=Ui_Create_Account_MainWindow03()
        self.ui.setupUi(self.window)           
        self.window.show()

   

    

# import resource file_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow01()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
