# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'POP_FACTORY_RESET.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 369)
        MainWindow.setMinimumSize(QtCore.QSize(612, 369))
        MainWindow.setMaximumSize(QtCore.QSize(612, 369))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 10, 20, 351))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(590, 10, 20, 351))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(12, 1, 587, 20))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(12, 349, 587, 20))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(100, 30, 411, 61))
        self.frame.setStyleSheet("border:2px solid black;\n"
"border-radius: 10px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(120, 10, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: rgb(255, 0, 255);\n"
"")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(91, 278, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(255, 0, 0), stop:1  rgb(158, 3, 3));\n"
"    \n"
"    \n"
"\n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"}\n"
"#pushButton:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(158, 3, 3), stop:1  rgb(255, 0, 0));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton:pressed {\n"
"background-color: rgb(255, 0, 0);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3_1.setGeometry(QtCore.QRect(239, 278, 131, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3_1.setFont(font)
        self.pushButton_3_1.setStyleSheet("#pushButton_3_1 {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(85, 255, 0), stop:1  rgb(7, 240, 151));\n"
"    \n"
"\n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"}\n"
"#pushButton_3_1:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(7, 240, 151), stop:1  rgb(85, 255, 0));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_3_1:pressed {\n"
"background-color: rgb(85, 255, 0);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_3_1.setObjectName("pushButton_3_1")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(390, 278, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("#pushButton_3 {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(37, 197, 255), stop:1  rgb(44, 69, 211));\n"
"    \n"
"    \n"
"border-radius:20px;\n"
"border-color: rgb(0, 0, 0);\n"
"border-style:outset;\n"
"border-width:3px;\n"
"}\n"
"#pushButton_3:hover {\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgb(44, 69, 211), stop:1  rgb(37, 197, 255));\n"
"padding-bottom: 5px;\n"
"padding-right: 5px;\n"
"}\n"
"\n"
"#pushButton_3:pressed {\n"
"background-color: rgb(37, 197, 255);\n"
"padding-top: 5px;\n"
"padding-left: 5px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(240, 160, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(240, 200, 181, 17))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(380, 110, 191, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 170, 0);")
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Factory Reset"))
        self.pushButton.setText(_translate("MainWindow", "Delete Now"))
        self.pushButton_3_1.setText(_translate("MainWindow", "Register"))
        self.pushButton_3.setText(_translate("MainWindow", "Close"))
        self.checkBox.setText(_translate("MainWindow", "All Test Data"))
        self.checkBox_2.setText(_translate("MainWindow", "All Specimen Data"))
        self.label_4.setText(_translate("MainWindow", "Test Count: "))
        self.pushButton_3.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(self.delete_data_batch)
       # self.pushButton_3_1.clicked.connect(self.open_new_window)
        self.load_data()
    
    def load_data(self):
        connection = sqlite3.connect("tyr.db")
        results=connection.execute("select count(*) FROM (select TEST_ID from TEST_MST LIMIT 500)") 
        for x in results:
            self.deleteing_count=str(x[0])                                 
        connection.close()
        
        connection = sqlite3.connect("tyr.db")
        results=connection.execute("select count(*) from TEST_MST") 
        for x in results:
            self.total_test_count=str(x[0])                                 
        connection.close()
        self.label_4.show()
        self.label_4.setText("Test Count: "+str(self.deleteing_count)+"/"+str(self.total_test_count))
        if(int(self.total_test_count) == 0):
            connection = sqlite3.connect("tyr.db")            
            with connection:        
                    cursor = connection.cursor()
                    cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name in ('TEST_MST','CYCLES_MST','GRAPH_MST','STG_GRAPH_MST','CYCLES_MST_CYCLIC','TEST_DATA','PEAK_MST','DEFLECTION_DATA','LOAD_DATA','LOW_VAL_MST','TEST_DATA_RADIAL')")                   
                    
            connection.commit()
            connection.close()
            
            connection = sqlite3.connect("tyr.db")            
            with connection:        
                    cursor = connection.cursor()
                    cursor.execute("PRAGMA auto_vacuum = FULL")
                    cursor.execute("vacuum")
                    
            connection.commit()
            connection.close()
            
            print("Sequences are also reinitiated")
        else:
            print("Still Data is not cleanned")
            
    
    def delete_data(self):
        if(self.checkBox.isChecked()):
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Warning)
            msg.setText("The 'to' date cannot be less than the 'from' date.")
            msg.setWindowTitle("Invalid Date Range")
            msg.setStandardButtons(QMessageBox.Ok | QMessageBox.Cancel)
            msg.exec_() 
            if msg == QMessageBox.Ok:           
                connection = sqlite3.connect("tyr.db")            
                with connection:        
                        cursor = connection.cursor()       
                        cursor.execute("DELETE FROM STG_GRAPH_MST")
                        cursor.execute("DELETE FROM GRAPH_MST ")
                        cursor.execute("DELETE FROM CYCLES_MST")
                        cursor.execute("DELETE FROM CYCLES_MST_CYCLIC")
                        cursor.execute("DELETE FROM TEST_MST")
                        cursor.execute("DELETE FROM TEST_DATA")
                        cursor.execute("DELETE FROM PEAK_MST") 
                        cursor.execute("DELETE FROM LOW_VAL_MST")
                        cursor.execute("DELETE FROM TEST_DATA_RADIAL")
                        cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name in ('TEST_MST','CYCLES_MST','GRAPH_MST','STG_GRAPH_MST','CYCLES_MST_CYCLIC','TEST_DATA','PEAK_MST','LOW_VAL_MST','DEFLECTION_DATA','LOAD_DATA','LOW_VAL_MST','TEST_DATA_RADIAL')")                    
                connection.commit()
                connection.close()
                print("ok - Deleted Test Data  ")
                self.label_4.show()        
        
          
        if(self.checkBox_2.isChecked()):            
            connection = sqlite3.connect("tyr.db")
            with connection:        
                    cursor = connection.cursor()       
                    cursor.execute("DELETE FROM SPECIMEN_MST")
                    cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name in ('SPECIMEN_MST')")
                    
            connection.commit()
            connection.close()
            print("ok - Deleted Specimen Data  ")
            self.label_4.show()
            
    def delete_data_batch(self):
        if(self.checkBox.isChecked()):         
                connection = sqlite3.connect("tyr.db")            
                with connection:        
                        cursor = connection.cursor()       
                        cursor.execute("DELETE FROM STG_GRAPH_MST")
                        cursor.execute("DELETE FROM TEST_MST WHERE TEST_ID IN (SELECT TEST_ID FROM TEST_MST LIMIT 500)")                    
                        cursor.execute("DELETE FROM CYCLES_MST WHERE TEST_ID NOT IN (SELECT TEST_ID FROM TEST_MST)")
                        cursor.execute("DELETE FROM TEST_DATA WHERE TEST_ID NOT IN (SELECT TEST_ID FROM TEST_MST)")
                        cursor.execute("DELETE FROM DEFLECTION_DATA WHERE TEST_ID NOT IN (SELECT TEST_ID FROM TEST_MST)")
                        cursor.execute("DELETE FROM LOAD_DATA WHERE TEST_ID NOT IN (SELECT TEST_ID FROM TEST_MST)")                    
                        cursor.execute("DELETE FROM CYCLES_MST_CYCLIC")
                        cursor.execute("DELETE FROM PEAK_MST")
                        cursor.execute("DELETE FROM LOW_VAL_MST")
                        cursor.execute("DELETE FROM TEST_DATA_RADIAL")
                        cursor.execute("DELETE FROM GRAPH_MST WHERE GRAPH_ID NOT IN (SELECT GRAPH_ID FROM CYCLES_MST)")  
                        #cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name in ('TEST_MST','CYCLES_MST','GRAPH_MST','STG_GRAPH_MST','CYCLES_MST_CYCLIC')")                    
                connection.commit()
                connection.close()
                print("ok - Deleted Test Data  ")
                self.label_4.show()        
        
          
        if(self.checkBox_2.isChecked()): 
                       
            connection = sqlite3.connect("tyr.db")
            with connection:        
                    cursor = connection.cursor()       
                    cursor.execute("DELETE FROM SPECIMEN_MST")
                    cursor.execute("DELETE FROM SQLITE_SEQUENCE WHERE name in ('SPECIMEN_MST')")
                    
            connection.commit()
            connection.close()
            print("ok - Deleted Specimen Data  ")
            self.label_4.show()
        
        self.load_data()
    
    
    def open_new_window(self):
        self.window = QtWidgets.QMainWindow()
        self.ui=TY_09_Ui_MainWindow()
        self.ui.setupUi(self.window)           
        self.window.show()    
       

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
