# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RQTAdministration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from UserManagement import Ui_User_Management
from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
import sqlite3
import getpass


class Ui_Administration(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(590, 410)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 20, 591, 400))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(30, 20, 531, 361))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(Images/17973908.jpg);\n"
"border-radius: 30px;\n"
"border: 1px solid black;")
        self.label.setMidLineWidth(9)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(70, 30, 441, 41))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("border-radius: 10px;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,  stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
"border:1px solid black;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(200,110, 151, 21)
        self.label_5.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border: none;")
        self.label_5.setObjectName("DateAndTime")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(40, 210, 511, 161))
        self.frame.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"\n"
"border-radius: 15px;\n"
"border:2px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.UserMangment = QtWidgets.QPushButton(self.frame)
        self.UserMangment.setGeometry(QtCore.QRect(20, 110, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UserMangment.setFont(font)
        self.UserMangment.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.UserMangment.setObjectName("UserMangment")
        self.MasterINformation = QtWidgets.QPushButton(self.frame)
        self.MasterINformation.setGeometry(QtCore.QRect(20, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.MasterINformation.setFont(font)
        self.MasterINformation.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.MasterINformation.setObjectName("MasterINformation")
        self.BreakApp = QtWidgets.QPushButton(self.frame)
        self.BreakApp.setGeometry(QtCore.QRect(190, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BreakApp.setFont(font)
        self.BreakApp.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.BreakApp.setObjectName("BreakApp")
        self.ConfigureTest = QtWidgets.QPushButton(self.frame)
        self.ConfigureTest.setGeometry(QtCore.QRect(190, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ConfigureTest.setFont(font)
        self.ConfigureTest.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.ConfigureTest.setObjectName("ConfigureTest")
        self.USBReport = QtWidgets.QPushButton(self.frame)
        self.USBReport.setGeometry(QtCore.QRect(20, 60, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.USBReport.setFont(font)
        self.USBReport.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.USBReport.setObjectName("USBReport")
        self.DateTimeSetting = QtWidgets.QPushButton(self.frame)
        self.DateTimeSetting.setGeometry(QtCore.QRect(360, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DateTimeSetting.setFont(font)
        self.DateTimeSetting.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.DateTimeSetting.setObjectName("DateTimeSetting")
        self.SpeedSetup = QtWidgets.QPushButton(self.frame)
        self.SpeedSetup.setGeometry(QtCore.QRect(360, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.SpeedSetup.setFont(font)
        self.SpeedSetup.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.SpeedSetup.setObjectName("SpeedSetup")
        self.FactoryReset = QtWidgets.QPushButton(self.frame)
        self.FactoryReset.setGeometry(QtCore.QRect(360, 10, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.FactoryReset.setFont(font)
        self.FactoryReset.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.FactoryReset.setObjectName("FactoryReset")
        self.EmailSetup_2 = QtWidgets.QPushButton(self.frame)
        self.EmailSetup_2.setGeometry(QtCore.QRect(190, 110, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.EmailSetup_2.setFont(font)
        self.EmailSetup_2.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.EmailSetup_2.setObjectName("EmailSetup_2")
#         self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.widget)
#         self.dateTimeEdit.setGeometry(QtCore.QRect(180, 110, 191, 21))
#         self.dateTimeEdit.setStyleSheet("background-color: rgba(0,0,0,0);\n"
# "border: none;")
#         self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.Pass = QtWidgets.QLineEdit(self.widget)
        self.Pass.setGeometry(QtCore.QRect(150, 142, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Pass.setFont(font)
        self.Pass.setAutoFillBackground(False)
        self.Pass.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Pass.setMaxLength(16)
        self.Pass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Pass.setCursorPosition(0)
        self.Pass.setPlaceholderText("")
        self.Pass.setClearButtonEnabled(False)
        self.Pass.setObjectName("Pass")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 142, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;")
        self.label_4.setObjectName("label_4")
        self.resetButton = QtWidgets.QPushButton(self.widget)
        self.resetButton.setGeometry(QtCore.QRect(460, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border: 1px solid black;\n"
"border-radius: 15px;")
        self.resetButton.setObjectName("resetButton")
        self.Procced = QtWidgets.QPushButton(self.widget)
        self.Procced.setGeometry(QtCore.QRect(350, 142, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Procced.setFont(font)
        self.Procced.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border: 1px solid black;\n"
"border-radius: 15px;")
        self.Procced.setObjectName("Procced")
        self.returnButton = QtWidgets.QPushButton(self.widget)
        self.returnButton.setGeometry(QtCore.QRect(450, 100, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.returnButton.setFont(font)
        self.returnButton.setStyleSheet("background-color: rgb(255, 142, 144);\n"
"border-radius: 15px;\n"
"border: 1px solid black;")
        self.returnButton.setObjectName("returnButton")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(190, 80, 171, 21))
        self.label_6 =QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(200, 220, 150, 20)

        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setGeometry(QtCore.QRect(40, 100, 131, 20))
        
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(10, 110, 240, 20)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(17)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Administration"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\">RATAN\'S ELECTRONICS</span></p></body></html>"))
        self.UserMangment.setText(_translate("MainWindow", "User Managment"))
        self.MasterINformation.setText(_translate("MainWindow", "Master Information"))
        self.BreakApp.setText(_translate("MainWindow", "Break App"))
        self.ConfigureTest.setText(_translate("MainWindow", "Configure Test"))
        self.USBReport.setText(_translate("MainWindow", "USB Reports Backup"))
        self.DateTimeSetting.setText(_translate("MainWindow", "DateTime Setting"))
        self.SpeedSetup.setText(_translate("MainWindow", "Speed Setup"))
        self.FactoryReset.setText(_translate("MainWindow", "Factory Reset"))
        self.EmailSetup_2.setText(_translate("MainWindow", "Email Setup"))
        self.label_4.setText(_translate("MainWindow", "Password :"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.Procced.setText(_translate("MainWindow", "Procced"))
        self.returnButton.setText(_translate("MainWindow", "RETURN"))
        self.label_2.setText(_translate("MainWindow", "Administration"))
        self.timer = QtCore.QTimer()
        self.timer.start(1)
        self.timer.setInterval(1000)
        self.timer.timeout.connect(self.device_date)
        self.frame.hide()
        self.Procced.clicked.connect(self.Administration_pass_Check)
        self.resetButton.clicked.connect(self.Reset_Button)
        self.returnButton.clicked.connect(MainWindow.close)
        self.First_Name_And_Last_Name()
        self.UserMangment.clicked.connect(self.Open_User_Management)
        # self.login_class_variables()
        self.current_login_by()
        
        




       


#     def login_class_variables(self, login_id):
       
#         print(login_id)

        

    def First_Name_And_Last_Name(self):
        pass
        # connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        # connection.execute("SELECT FIRST_NAME, LAST_NAME FROM USER_MST WHERE USER_NAME='"+str(self.)")

    

    def device_date(self):
        self.label_5.setText(datetime.datetime.now().strftime("%d %b %Y %H:%M:%S"))

    def Administration_pass_Check(self):
        self.go_ahead = 0
        self.Pass_1 = str(self.Pass.text())
        connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        results = connection.execute("SELECT PASSWORD FROM GLOBAL_VAR WHERE PASSWORD='"+str(self.Pass_1)+"'")
       
        
        for x in results:
            if (str(x[0]) == str(self.Pass_1)):
                self.go_ahead = 1
            else:     
                self.go_ahead = 0



        if ( self.go_ahead == 1):
            self.frame.show()
            self.label_6.hide()
            connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
            results = connection.execute("SELECT LOGIN_ID FROM GLOBAL_VAR WHERE PASSWORD='"+str(self.Pass_1)+"'")
            for x in results:
                self.login = str(x)
                print(x, "login id ")
            
                
            
            

        else:
            self.label_6.setText("Enter The Correct Password")
            self.label_6.show()
            self.frame.hide() 
        
        self.current_login_by()
        


    def current_login_by(self):
        # connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        # results = connection.execute("SELECT FIRST_NAME, LAST_NAME WHERE USER_ID = ")
        connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        # results = connection.execute("SELECT FIRST_NAME, LAST_NAME FROM USER_MST WHERE LOGIN_ID ='"+str(self.login)+"'")
        self.query = "SELECT FIRST_NAME, LAST_NAME FROM USER_MST WHERE LOGIN_ID = ?"
        results = connection.execute(self.query, (self.login,))


        for x in results:
            self.label_8.setText(str(x[0], str(x[1])))

            print(self.label_8, "ccccccc")        
        

    def Reset_Button(self):
        self.Pass.setText("")
        self.label_6.hide()
        self.frame.hide() 


    def Open_User_Management(self):
        self.window =QtWidgets.QMainWindow()
        self.ui = Ui_User_Management()
        self.ui.setupUi(self.window)
        self.window.show()
                                
    
#     def login_class_variables(self): 

#         from login import Ui_MainWindow
#         self.window = QtWidgets.QMainWindow()
#         self.ui=Ui_MainWindow() 
#         self.ui.input_fild()  
#         self.ui.setupUi(self.window)
#         self.window.show()    


# import resource file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Administration()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
