# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UserManagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import datetime
import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_User_Management(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1012, 617)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 971, 601))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 10, 951, 571))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-image: url(Images/17973908.jpg);\n"
"border-radius: 30px;\n"
"border: 1px solid black;")
        self.label.setMidLineWidth(9)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 701, 41))
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setStyleSheet("border-radius: 10px;\n"
"background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5,  stop:0.504819 rgba(255, 255, 255, 255), stop:0.79 rgba(255, 255, 255, 255), stop:1 rgba(255, 158, 158, 255));\n"
"border:1px solid black;")
        self.label_3.setObjectName("label_3")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(530, 100, 401, 421))
        self.frame.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"\n"
"border-radius: 15px;\n"
"border:2px solid black;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.Line_UserID = QtWidgets.QLineEdit(self.frame)
        self.Line_UserID.setGeometry(QtCore.QRect(170, 10, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_UserID.setFont(font)
        self.Line_UserID.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_UserID.setAutoFillBackground(False)
        self.Line_UserID.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_UserID.setMaxLength(12)
        self.Line_UserID.setCursorPosition(0)
        self.Line_UserID.setPlaceholderText("")
        self.Line_UserID.setClearButtonEnabled(False)
        self.Line_UserID.setObjectName("Line_UserID")
        self.AddButton = QtWidgets.QPushButton(self.frame)
        self.AddButton.setGeometry(QtCore.QRect(30, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.AddButton.setFont(font)
        self.AddButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.AddButton.setObjectName("AddButton")
        self.L_User_ID = QtWidgets.QLabel(self.frame)
        self.L_User_ID.setGeometry(QtCore.QRect(20, 10, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_User_ID.setFont(font)
        self.L_User_ID.setStyleSheet("border: none;")
        self.L_User_ID.setObjectName("L_User_ID")
        self.resetButton = QtWidgets.QPushButton(self.frame)
        self.resetButton.setGeometry(QtCore.QRect(300, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resetButton.setFont(font)
        self.resetButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.resetButton.setObjectName("resetButton")
        self.DeleteButton = QtWidgets.QPushButton(self.frame)
        self.DeleteButton.setGeometry(QtCore.QRect(210, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.DeleteButton.setObjectName("DeleteButton")
        self.DeleteButton.setEnabled(False)
        self.UpdateButton = QtWidgets.QPushButton(self.frame)
        self.UpdateButton.setGeometry(QtCore.QRect(120, 380, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.UpdateButton.setFont(font)
        self.UpdateButton.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-radius: 15px;")
        self.UpdateButton.setObjectName("UpdateButton")
        self.UpdateButton.setEnabled(False)
        self.L_First_Name = QtWidgets.QLabel(self.frame)
        self.L_First_Name.setGeometry(QtCore.QRect(20, 50, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_First_Name.setFont(font)
        self.L_First_Name.setStyleSheet("border: none;")
        self.L_First_Name.setObjectName("L_First_Name")
        self.Line_FirstName = QtWidgets.QLineEdit(self.frame)
        self.Line_FirstName.setGeometry(QtCore.QRect(170, 50, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_FirstName.setFont(font)
        self.Line_FirstName.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_FirstName.setAutoFillBackground(False)
        self.Line_FirstName.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_FirstName.setMaxLength(12)
        self.Line_FirstName.setCursorPosition(0)
        self.Line_FirstName.setPlaceholderText("")
        self.Line_FirstName.setClearButtonEnabled(False)
        self.Line_FirstName.setObjectName("Line_FirstName")
        self.L_Last_Name = QtWidgets.QLabel(self.frame)
        self.L_Last_Name.setGeometry(QtCore.QRect(20, 90, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_Last_Name.setFont(font)
        self.L_Last_Name.setStyleSheet("border: none;")
        self.L_Last_Name.setObjectName("L_Last_Name")
        self.Line_LastName = QtWidgets.QLineEdit(self.frame)
        self.Line_LastName.setGeometry(QtCore.QRect(170, 90, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_LastName.setFont(font)
        self.Line_LastName.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_LastName.setAutoFillBackground(False)
        self.Line_LastName.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_LastName.setMaxLength(12)
        self.Line_LastName.setCursorPosition(0)
        self.Line_LastName.setPlaceholderText("")
        self.Line_LastName.setClearButtonEnabled(False)
        self.Line_LastName.setObjectName("Line_LastName")
        self.L_RePassword = QtWidgets.QLabel(self.frame)
        self.L_RePassword.setGeometry(QtCore.QRect(20, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_RePassword.setFont(font)
        self.L_RePassword.setStyleSheet("border: none;")
        self.L_RePassword.setObjectName("L_RePassword")
        self.Line_RePassword = QtWidgets.QLineEdit(self.frame)
        self.Line_RePassword.setGeometry(QtCore.QRect(170, 210, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_RePassword.setFont(font)
        self.Line_RePassword.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_RePassword.setAutoFillBackground(False)
        self.Line_RePassword.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_RePassword.setMaxLength(12)
        self.Line_RePassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Line_RePassword.setCursorPosition(0)
        self.Line_RePassword.setPlaceholderText("")
        self.Line_RePassword.setClearButtonEnabled(False)
        self.Line_RePassword.setObjectName("Line_RePassword")
        self.L_EmailID = QtWidgets.QLabel(self.frame)
        self.L_EmailID.setGeometry(QtCore.QRect(20, 250, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_EmailID.setFont(font)
        self.L_EmailID.setStyleSheet("border: none;")
        self.L_EmailID.setObjectName("L_EmailID")
        self.Line_EmailID = QtWidgets.QLineEdit(self.frame)
        self.Line_EmailID.setGeometry(QtCore.QRect(170, 250, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_EmailID.setFont(font)
        self.Line_EmailID.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_EmailID.setAutoFillBackground(False)
        self.Line_EmailID.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_EmailID.setMaxLength(30)
        self.Line_EmailID.setCursorPosition(0)
        self.Line_EmailID.setPlaceholderText("")
        self.Line_EmailID.setClearButtonEnabled(False)
        self.Line_EmailID.setObjectName("Line_EmailID")
        self.L_PhoneNo = QtWidgets.QLabel(self.frame)
        self.L_PhoneNo.setGeometry(QtCore.QRect(20, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_PhoneNo.setFont(font)
        self.L_PhoneNo.setStyleSheet("border: none;")
        self.L_PhoneNo.setObjectName("L_PhoneNo")
        self.Line_PhoneNo = QtWidgets.QLineEdit(self.frame)
        self.Line_PhoneNo.setGeometry(QtCore.QRect(170, 290, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_PhoneNo.setFont(font)
        self.Line_PhoneNo.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.Line_PhoneNo.setAutoFillBackground(False)
        self.Line_PhoneNo.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_PhoneNo.setMaxLength(10)
        self.Line_PhoneNo.setCursorPosition(0)
        self.Line_PhoneNo.setPlaceholderText("")
        self.Line_PhoneNo.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.Line_PhoneNo.setClearButtonEnabled(False)
        self.Line_PhoneNo.setObjectName("Line_PhoneNo")
        self.L_Role_Name = QtWidgets.QLabel(self.frame)
        self.L_Role_Name.setGeometry(QtCore.QRect(20, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_Role_Name.setFont(font)
        self.L_Role_Name.setStyleSheet("border: none;")
        self.L_Role_Name.setObjectName("L_Role_Name")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(170, 330, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:10px;\n"
"border: 1px solid black;")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Line_Password = QtWidgets.QLineEdit(self.frame)
        self.Line_Password.setGeometry(QtCore.QRect(170, 170, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_Password.setFont(font)
        self.Line_Password.setAutoFillBackground(False)
        self.Line_Password.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_Password.setMaxLength(12)
        self.Line_Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Line_Password.setCursorPosition(0)
        self.Line_Password.setPlaceholderText("")
        self.Line_Password.setClearButtonEnabled(False)
        self.Line_Password.setObjectName("Line_Password")
        self.Line_LoginID = QtWidgets.QLineEdit(self.frame)
        self.Line_LoginID.setGeometry(QtCore.QRect(170, 130, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.Line_LoginID.setFont(font)
        self.Line_LoginID.setAutoFillBackground(False)
        self.Line_LoginID.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;")
        self.Line_LoginID.setMaxLength(12)
        self.Line_LoginID.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Line_LoginID.setCursorPosition(0)
        self.Line_LoginID.setPlaceholderText("")
        self.Line_LoginID.setClearButtonEnabled(False)
        self.Line_LoginID.setObjectName("Line_LoginID")
        self.L_Password = QtWidgets.QLabel(self.frame)
        self.L_Password.setGeometry(QtCore.QRect(20, 170, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_Password.setFont(font)
        self.L_Password.setStyleSheet("border: none;")
        self.L_Password.setObjectName("L_Password")
        self.L_LoginID = QtWidgets.QLabel(self.frame)
        self.L_LoginID.setGeometry(QtCore.QRect(20, 130, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.L_LoginID.setFont(font)
        self.L_LoginID.setStyleSheet("border: none;")
        self.L_LoginID.setObjectName("L_LoginID")


        self.label_5_Success = QtWidgets.QLabel(self.widget)
        self.label_5_Success.setGeometry(QtCore.QRect(570, 80, 320, 25))
        self.label_5_Success.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label_5_Success.setObjectName("label_5_Success")
        self.label_5_Success.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5_Success.setFont(font)
        self.label_5_Success.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)


        self.label_5_Worning = QtWidgets.QLabel(self.widget)
        self.label_5_Worning.setGeometry(QtCore.QRect(570, 80, 320, 25))
        self.label_5_Worning.setInputMethodHints(QtCore.Qt.ImhHiddenText)
        self.label_5_Worning.setObjectName("label_5_Worning")
        self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_5_Worning.setFont(font)
        self.label_5_Worning.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.sdButton = QtWidgets.QPushButton(self.widget)
        self.sdButton.setGeometry(QtCore.QRect(710, 540, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.sdButton.setFont(font)
        self.sdButton.setStyleSheet("background-color: rgb(255, 142, 144);\n"
"border-radius: 15px;\n"
"border-color: rgb(0, 0, 0);\n"
"border: 1px solid black;")
        self.sdButton.setObjectName("sdButton")
        self.rebootButton = QtWidgets.QPushButton(self.widget)
        self.rebootButton.setGeometry(QtCore.QRect(70, 540, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.rebootButton.setFont(font)
        self.rebootButton.setStyleSheet("background-color: rgb(255, 142, 144);\n"
"border-radius: 15px;\n"
"border: 1px solid black;")
        self.rebootButton.setObjectName("rebootButton")
        self.label_6_dateTime = QtWidgets.QLabel(self.widget)
        self.label_6_dateTime.setGeometry(QtCore.QRect(380, 70, 201, 31))
        self.label_6_dateTime.setObjectName("label_6_dateTime")
        self.ReturnButton = QtWidgets.QPushButton(self.widget)
        self.ReturnButton.setGeometry(QtCore.QRect(810, 540, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ReturnButton.setFont(font)
        self.ReturnButton.setStyleSheet("background-color: rgb(255, 142, 144);\n"
"border-radius: 15px;\n"
"border: 1px solid black;")
        self.ReturnButton.setObjectName("ReturnButton")
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        self.tableWidget.setGeometry(QtCore.QRect(35, 101, 481, 421))
        font = QtGui.QFont()
        font.setFamily("Arial Narrow")
        font.setPointSize(10)
        font.setUnderline(False)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("\n"
"border:2px solid black;")
        self.tableWidget.setLineWidth(3)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        # self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(16)
        self.tableWidget.setDragEnabled(True)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setWordWrap(True)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setColumnWidth(0, 150)
        self.tableWidget.setObjectName("tableWidget")
        
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(100)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(39)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(False)
        self.tableWidget.verticalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(28)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(25)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setGeometry(QtCore.QRect(40, 65, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(400, 540, 191, 21))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Management"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600; text-decoration: underline;\">RATAN\'S ELECTRONICS</span></p></body></html>"))
        self.AddButton.setText(_translate("MainWindow", "ADD"))
        self.L_User_ID.setText(_translate("MainWindow", "User ID :"))
        self.resetButton.setText(_translate("MainWindow", "RESET"))
        self.DeleteButton.setText(_translate("MainWindow", "DELETE"))
        self.UpdateButton.setText(_translate("MainWindow", "UPDATE"))
        self.L_First_Name.setText(_translate("MainWindow", "First Name :"))
        self.L_Last_Name.setText(_translate("MainWindow", "Last Name :"))
        self.L_RePassword.setText(_translate("MainWindow", "Re-Password :"))
        self.L_EmailID.setText(_translate("MainWindow", "Email ID :"))
        self.L_PhoneNo.setText(_translate("MainWindow", "Phone No. :"))
        self.L_Role_Name.setText(_translate("MainWindow", "Role Name :"))
        self.comboBox.setCurrentText(_translate("MainWindow", "OPERATOR"))
        self.comboBox.setItemText(0, _translate("MainWindow", "OPERATOR"))
        self.comboBox.setItemText(1, _translate("MainWindow", "SUPERVISOR"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ADMIN"))
        self.L_Password.setText(_translate("MainWindow", "Password :"))
        self.L_LoginID.setText(_translate("MainWindow", "Login ID :"))
        self.label_5_Success.setText(_translate("MainWindow", "Please Enter Field"))
        self.sdButton.setText(_translate("MainWindow", "SHUT DOWN"))
        self.rebootButton.setText(_translate("MainWindow", "REBOOT"))
        self.label_6_dateTime.setText(_translate("MainWindow", "Date And Time Label"))
        self.ReturnButton.setText(_translate("MainWindow", "RETURN"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "USER_ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FIRST_NAME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "LAST_NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "LOGIN_ID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PASSWORD"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "RE-PASSWORD"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "EMAIL_ID"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "PHONE_NO."))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "ROLE_NAME"))
        self.label_14.setText(_translate("MainWindow", "User Management"))
        self.label_2.setText(_translate("MainWindow", "Login By : Hiral Panchal"))
        self.ReturnButton.clicked.connect(MainWindow.close)
        self.time = QtCore.QTimer()
        self.time.start(1)
        self.time.setInterval(1000)
        self.time.timeout.connect(self.DateAndTime)
        self.resetButton.clicked.connect(self.Reset_Field)
        self.AddButton.clicked.connect(self.Add_User)
        self.Load_Data_To_Table()
        #self.tableWidget.itemDoubleClicked.connect(self.Selected_Recoard)
        self.tableWidget.itemSelectionChanged.connect(self.Selected_Recoard)
        self.DeleteButton.clicked.connect(self.Delete_User)
        self.UpdateButton.clicked.connect(self.Update_User)
        self.label_5_Worning.hide()
        self.login_by()
        

    def login_by(self):
        pass    

    def Update_User(self):
        self.label_5_Worning.hide()
        self.user_id = str(self.Line_UserID.text())
        self.first_name = str(self.Line_FirstName.text())
        self.last_name = str(self.Line_LastName.text())
        self.login_id = str(self.Line_LoginID.text())
        self.password = str(self.Line_Password.text()) 
        self.re_password = str(self.Line_RePassword.text())
        self.email_id = str(self.Line_EmailID.text())
        self.phone_no = str(self.Line_PhoneNo.text())
        self.role_name = str(self.comboBox.currentText())

        connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        
        results = connection.execute("SELECT USER_ID FROM USER_MST WHERE USER_ID = '"+str(self.user_id)+"'")
        self.go_update = 0
        for x in results:
            if (str(x[0]) == str(self.user_id)):
                self.go_update = 1
            else:
                self.go_update = 0   


        if (int(self.go_update == 1)):
            self.label_5_Worning.hide()
            connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
            cursor = connection.cursor()
            cursor.execute("UPDATE USER_MST SET FIRST_NAME = '"+str(self.first_name)+"', LAST_NAME = '"+str(self.last_name)+"', LOGIN_ID = '"+str(self.login_id)+"', PASSWORD = '"+str(self.password)+"', RE_PASSWORD = '"+str(self.re_password)+"', EMAIL_ID = '"+str(self.email_id)+"', PHONE_NO = '"+str(self.phone_no)+"', ROLE_NAME = '"+str(self.role_name)+"' WHERE USER_ID = '"+str(self.user_id)+"'  ")
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n" "background-color: rgb(0, 255, 0);\n" "border:1px solid black;\n" "border-radius: 12px;")
            self.label_5_Worning.setText("User's Details Updated Successfully!")
            self.label_5_Worning.show()
            connection.commit()
            connection.close()
            self.Load_Data_To_Table()
            
        else:
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("User Not Found")
            self.label_5_Worning.show()

        connection.close()    


    def Delete_User(self):

        self.user_id = str(self.Line_UserID.text())
        if (self.user_id != ""):
                connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
                cursor = connection.cursor()
                cursor.execute("DELETE FROM USER_MST WHERE USER_ID ='"+str(self.user_id)+"'")    #and FIRST_NAME='"+str(self.first_name)+"' and LAST_NAME = '"+str(self.last_name)+"' and LOGIN_ID = '"+str(self.login_id)+"' and PASSWORD = '"+str(self.password)+"' and RE_PASSWORD = '"+str(self.re_password)+"' and EMAIL_ID = '"+str(self.email_id)+"' and PHONE_NO = '"+str(self.phone_no)+"' and ROLE_NAME = '"+str(self.role_name)+"' ")
                # print(cursor.rowcount, "ccccccccc")
                # print(self.user_id, "user iddddddddddddd")
                connection.commit()

                if cursor.rowcount > 0:
                    # print("if event fired ")
                    self.label_5_Success.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")    
                    self.label_5_Success.setText("User Deleted Successfully!")
                    self.label_5_Success.show()
                    self.Reset_Field() 
                    self.Load_Data_To_Table()  
                else:
                    self.label_5_Worning.setText("User not found or deletion failed!")
                    self.label_5_Worning.show()
                    # print("else event fired.....................")
                connection.close()
        else:
            self.label_5_Worning.setText("Please Select The User To Be Deleted!")
                    
        

    def Selected_Recoard(self):
        # self.label_5_Success.hide()
        self.UpdateButton.setEnabled(True)
        self.DeleteButton.setEnabled(True)
        self.AddButton.setEnabled(False)
        self.selected_item = self.tableWidget.selectedItems()
        # if self.selected_item:
        self.selected_row_data = []
        for x in self.selected_item:
            self.selected_row_data.append(str(x.text()))
        #     print(self.selected_row_data)
            

            if len(self.selected_row_data) >= 9:
                self.Line_UserID.setText(self.selected_row_data[0])
                self.Line_FirstName.setText(self.selected_row_data[1])
                self.Line_LastName.setText(self.selected_row_data[2])
                self.Line_LoginID.setText(self.selected_row_data[3])
                self.Line_Password.setText(self.selected_row_data[4])
                self.Line_RePassword.setText(self.selected_row_data[5])
                self.Line_EmailID.setText(self.selected_row_data[6])
                self.Line_PhoneNo.setText(self.selected_row_data[7])
                self.comboBox.setCurrentText(self.selected_row_data[8])

            elif (self.Line_UserID != "" and self.Line_FirstName != "" and self.Line_LastName != "" and self.Line_LoginID != "" and self.Line_Password != "" and self.Line_RePassword != "" and self.Line_EmailID != "" and self.Line_PhoneNo != ""):
                # self.label_5_Worning.hide()
                
                self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
                self.label_5_Worning.setText("Click the reset button to 'Add' the user")
                self.label_5_Worning.show()
             
            self.label_5_Success.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Success.setText("Please Enter Field")
                 

         
                
                

                


        
    def Load_Data_To_Table(self):
        connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
        
        results = connection.execute("SELECT * FROM USER_MST ")
        self.tableWidget.clearContents()
        tablerow = 0
        
        # print(tablerow, " table row number ")

        for x in results:
            # print(x)
            self.tableWidget.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(str(x[0])))
            self.tableWidget.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(str(x[1])))
            self.tableWidget.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(str(x[2])))
            self.tableWidget.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(str(x[3])))
            self.tableWidget.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(str(x[4])))
            self.tableWidget.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(str(x[5])))
            self.tableWidget.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(str(x[6])))
            self.tableWidget.setItem(tablerow, 7, QtWidgets.QTableWidgetItem(str(x[7])))
            self.tableWidget.setItem(tablerow, 8, QtWidgets.QTableWidgetItem(str(x[8])))
            tablerow = tablerow + 1
            # print(tablerow, "inside for loop row no. ")
            # print(x[0])
        connection.close()    

            

            
           
    def Add_User(self):
        
        # self.label_5_Worning.show()
        self.user_id = str(self.Line_UserID.text())
        self.first_name = str(self.Line_FirstName.text())
        self.last_name = str(self.Line_LastName.text())
        self.login_id = str(self.Line_LoginID.text())
        self.password = str(self.Line_Password.text()) 
        self.re_password = str(self.Line_RePassword.text())
        self.email_id = str(self.Line_EmailID.text())
        self.phone_no = str(self.Line_PhoneNo.text())
        self.role_name = str(self.comboBox.currentText())
        

        if (self.user_id != "" and self.first_name != "" and self.last_name != "" and self.login_id != "" and self.password != "" and self.re_password != "" and self.email_id != "" and self.phone_no != ""):
            connection = sqlite3.connect("RATAN'S_ELECTRONICS.db")
            cursor = connection.cursor()
            cursor.execute("INSERT INTO USER_MST(USER_ID, FIRST_NAME, LAST_NAME, LOGIN_ID, PASSWORD, RE_PASSWORD, EMAIL_ID, PHONE_NO, ROLE_NAME) VALUES('"+str(self.user_id)+"', '"+str(self.first_name)+"', '"+str(self.last_name)+"', '"+str(self.login_id)+"', '"+str(self.password)+"', '"+str(self.re_password)+"', '"+str(self.email_id)+"', '"+str(self.phone_no)+"', '"+str(self.role_name)+"')")
            connection.commit()
            connection.close()
            
            self.label_5_Success.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(0, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Success.setText("New User Added Succecfully !")
            self.label_5_Success.show()

            
            self.Reset_Field()
            self.Load_Data_To_Table()
        elif (self.user_id == "" and self.first_name == "" and self.last_name == "" and self.login_id == "" and self.password == "" and self.re_password == "" and self.email_id == "" and self.phone_no == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter Field")
            self.label_5_Worning.show()    
        elif (self.user_id == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The User ID")
            self.label_5_Worning.show() 
        elif (self.first_name == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The First Name")
            self.label_5_Worning.show() 
        elif (self.last_name == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Last Name") 
        elif (self.login_id == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Login ID")
            self.label_5_Worning.show()
        elif (self.password == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Password")
            self.label_5_Worning.show()
        elif (self.re_password == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Re-Password")
            self.label_5_Worning.show()
        elif (self.email_id == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Email ID")
            self.label_5_Worning.show() 
        elif (self.phone_no == ""):
            self.label_5_Worning.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 0);\n"
"border:1px solid black;\n"
"border-radius: 12px;")
            self.label_5_Worning.setText("Please Enter The Phone No.")
            self.label_5_Worning.show()                         
  
               


               
    def Reset_Field(self):
        self.Line_UserID.setText("")
        self.Line_FirstName.setText("")
        self.Line_LastName.setText("")
        self.Line_LoginID.setText("")
        self.Line_Password.setText("")
        self.Line_RePassword.setText("")
        self.Line_EmailID.setText("")
        self.Line_PhoneNo.setText("")
        self.comboBox.setCurrentText("OPERATOR")
        self.label_5_Success.show()
        self.label_5_Worning.hide()
        self.AddButton.setEnabled(True)
        self.UpdateButton.setEnabled(False)
        self.DeleteButton.setEnabled(False)
        
        
        

    def DateAndTime(self):
        self.label_6_dateTime.setText(datetime.datetime.now().strftime("%d %b %Y %H:%M:%S"))
            
# import resource file_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_User_Management()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
